# config/packages/twig.yaml
twig:
    default_path: '%kernel.project_dir%/templates'
    # Add cache and other configurations as needed
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null